### ISSUE TITLE
Support for cmark-gfm?

### ISSUE THREAD

**Issue by ravanscafi** [asaaki/cmark.ex#30]
Hello!

I'm looking for a NIF for [GitHub Flavored Markdown version of cmark](https://github.com/github/cmark-gfm). Would it be possible for this library to support it?
Or it should sit on a separate repo?

I'm happy to contribute, even though I'm totally noob on the subject :)

Thanks

**Comment by asaaki** [comment]
I haven't looked at it. Also currently I'm not doing much Elixir these days.
If the C API is similar/identical to the "pure" cmark library, switching should not be too difficult.
OTOH I think we should have a fork for the "-gfm" aspects, so people could choose to use either of them. (Dunno if folks wouldn't want to opt-in to the additional features.)

**Comment by ravanscafi** [comment]
Thanks for the quick response @asaaki :)
I will try to fork it this week to create the `gfm` version
