### ISSUE TITLE
A way to white list safe tags when using to_safe_html

### ISSUE THREAD

**Issue by nickjj** [asaaki/cmark.ex#31]
Hi,

Right now if you use `to_safe_html`, it will strip out image tags but imagine a scenario where you're creating a comment box similar to GitHub issues where you want to allow users to upload images.

It would be nice if `to_safe_html` allowed you to set a list of allowed tags.

**Comment by josevalim** [comment]
The underlying C library does not provide this possibility, so it is quite unlikely this one would do it. To quote it directly:

> By default, the library will scrub raw HTML and potentially dangerous links (javascript:, vbscript:, data:, file:).
>
> To allow these, use the option CMARK_OPT_UNSAFE (or --unsafe) with the command line program. If doing so, we recommend you use a HTML sanitizer specific to your needs to protect against XSS attacks.

FWIW, when I upload an image to GitHub, they emit the proper markdown for it (they do not emit HTML).

**Comment by asaaki** [comment]
Thank you @josevalim for answering, I completely missed the notification for this issue here.
