### ISSUE TITLE
Code Highlighting

### ISSUE THREAD

**Issue by solomonhawk** [asaaki/cmark.ex#35]
I haven't used the Cmark parser before with ExDoc but I tried it because Earmark doesn't support formatting markdown nested inside html tags. Cmark does, but my output has no code highlighting.

Is this expected?

All I've done is add `{:cmark, "~> 0.7"}` to my deps, add `markdown_processor: ExDoc.Markdown.Cmark`, and build the docs. You can see the result below:

![image](https://user-images.githubusercontent.com/1037707/81177779-31f05100-8f75-11ea-8dce-e9b9984e67d9.png)

I'm happy to provide additional information if it's helpful!

Thanks

**Comment by josevalim** [comment]
This is more of an issue with ExDoc, as it is the one doing code highlighting. However, note that we removed Cmark support on master, because future ExDoc versions will work with the markdown AST, so I am afraid you don't really have a long term option at the moment.

**Comment by solomonhawk** [comment]
@josevalim Understood. I can feel myself grasping at straws at the moment trying to find a workable solution.

I'm hopeful that Earmark will eventually solve this in order to resolve https://github.com/pragdave/earmark/issues/228. It's a tricky problem, but marking html elements with a special attribute to opt-in to nested markdown parsing seems like a sane path forward.

In the meantime I will explore writing a custom transformer to do this and if successful will try to share that around.

I expanded on my use case in the issue on the earmark repo.

Thanks as usual for all that you continue to do for this lovely community, José.
