### ISSUE TITLE
Adding templates for PR / Issues and CoC

### ISSUE THREAD

**Issue by floriank** [asaaki/cmark.ex#42]
If this repository gets more attention, should we add a template for

* Issues
* Pull Requests

and a Code of Conduct? For the sake of simplicity, I'd just use either one of:

* https://github.com/stevemao/github-issue-templates
* or the issue template from [elixir](https://github.com/elixir-lang/elixir/blob/master/.github/ISSUE_TEMPLATE.md) with the appropriate modifications

The Code of Conduct can be created [via Github itself](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project).

**Comment by asaaki** [comment]
Sounds great.
Will take care of the CoC (because email address).
Feel free to check for suitable issue and PR templates. 💙
